### ISSUE TITLE
Regarding the rs_data module in the generate_data_ncf.py file.

### ISSUE THREAD

**Issue by JiaXiaotun** [KNODIS-Research-Group/neural-cf-for-groups#1]
Can you point out where the rs_data module is in this file? I'm not sure of its location.

**Comment by JorgeDuenasLerin** [comment]
Sorry, this file is part of another experiment, it must not be here and is not used in this paper.

Long explanation
In the paper Neural Collaborative Filtering, Xiangnan 2017
https://arxiv.org/pdf/1708.05031.pdf

The researcher used a negative sampling in each epoch.
https://github.com/hexiangnan/neural_collaborative_filtering/blob/4aab159e81c44b062c091bdaed0ab54ac632371f/NeuMF.py#L135

We are training more models and as it takes too long in each epoch to generate the samples, the script generate_data_ncf, generates 3000 datasets with negative sampling and stores them.

**Comment by JiaXiaotun** [comment]
I get it. Thanks!




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Jorge Dueñas ***@***.***&gt;; 
发送时间: 2023年3月22日(星期三) 下午5:26
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [KNODIS-Research-Group/neural-cf-for-groups] Regarding the rs_data module in the generate_data_ncf.py file. (Issue #1)





 
Sorry, this file is part of another experiment, it must not be here and is not used in this paper.
 
Long explanation
 In the paper Neural Collaborative Filtering, Xiangnan 2017
 https://arxiv.org/pdf/1708.05031.pdf
 
The researcher used a negative sampling in each epoch.
 https://github.com/hexiangnan/neural_collaborative_filtering/blob/4aab159e81c44b062c091bdaed0ab54ac632371f/NeuMF.py#L135
 
We are training more models and as it takes too long in each epoch to generate the samples, the script generate_data_ncf, generates 3000 datasets with negative sampling and stores them.

**Comment by JiaXiaotun** [comment]
I get it. Thanks!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "KNODIS-Research-Group/neural-cf-for-groups"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月22日(星期三) 下午5:26
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [KNODIS-Research-Group/neural-cf-for-groups] Regarding the rs_data module in the generate_data_ncf.py file. (Issue #1)





 
Sorry, this file is part of another experiment, it must not be here and is not used in this paper.
 
Long explanation
 In the paper Neural Collaborative Filtering, Xiangnan 2017
 https://arxiv.org/pdf/1708.05031.pdf
 
The researcher used a negative sampling in each epoch.
 https://github.com/hexiangnan/neural_collaborative_filtering/blob/4aab159e81c44b062c091bdaed0ab54ac632371f/NeuMF.py#L135
 
We are training more models and as it takes too long in each epoch to generate the samples, the script generate_data_ncf, generates 3000 datasets with negative sampling and stores them.
